# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b92d2e6a3aa464eeae4dfcdeebb2abe4c58d3e74de72391113a9c263b9a03f1543bc133418a0e9725f6ee9f877c55483692a665beb8f8a54f8c64d6b0b52b558

test:
  secret_key_base: b36180edd88e9532fea92ed424ac1f131168f0bb76890ccffe4eecf192b52a37b772cfbaa1b0ff945b4d6b5d54af5b107457f1e9eb542b4da62701c55a66a4d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
